# Setup
title:        David Tellez
tagline:      Research | Deep Learning | Medical Imaging
baseurl:      ""
paginate:     1

# About/contact
author: davidtellez
name: David Tellez
url: "https://davidtellez.github.io/"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
