# Setup
title:        David Tellez
tagline:      Research | Deep Learning | Medical Imaging
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       
  url:        

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown