# Setup
title:        David Tellez
tagline:      Research | Deep Learning | Medical Imaging
baseurl:      "https://davidtellez.github.io/"
paginate:     1

# About/contact
author:       davidtellez
  name:       David Tellez 
  url:        https://davidtellez.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
